name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x
    - name: Use NuGet cache
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore packages
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
    - name: Generate coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@4.6.1
      with:
        reports: tests/**/coverage.cobertura.xml
        targetdir: coveragereport
        reporttypes: Html
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:	
        name: Coverage Report
        path: coveragereport
